### ISSUE TITLE
call query method crash when network not connected

### ISSUE THREAD

**Issue by walterFeng** [graphql-rust/graphql-client#309]
It'll crash when I call GraphQlUtil.query.  And try-catch not working in here. 
It is work fine when network connected.

```dart
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:graphql/client.dart';
import 'package:shared_preferences/shared_preferences.dart';

final HttpLink _httpLink = HttpLink(
  uri: baseUrl,
);

final AuthLink _authLink = AuthLink(getToken: () async {
  SharedPreferences prefs = await SharedPreferences.getInstance();
  String token = prefs.getString('token');
  return token != null ? 'Bearer $token' : '';
});

final Link _link = _authLink.concat(_httpLink);

GraphQLClient _client;

class GraphQlUtil {
  static GraphQLClient client() {
    _client ??= GraphQLClient(
      link: _link,
      cache: InMemoryCache(),
    );
    return _client;
  }

  static Future<dynamic> query(String document,
      [Map<String, dynamic> variables, FetchPolicy fetchPolicy]) async {
    QueryResult result;
    try {
      result = await client().query(QueryOptions(
          documentNode: gql(document),
          variables: variables,
          fetchPolicy: FetchPolicy.networkOnly));
      if (result.hasException) {
        throw result.exception;
      }
      return result.data;
    } catch (e) {
      try {
        throw GraphQlError(exception: result.exception);
      } catch (sub) {
        if (sub is GraphQlError) {
          throw sub;
        } else {
          print(sub);
          throw e;
        }
      }
    }
  }
}
```

this is error log:
```js
E/flutter (29368): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'host' was called on null.
E/flutter (29368): Receiver: null
E/flutter (29368): Tried calling: host
E/flutter (29368): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (29368): #1      translateNetworkFailure (package:graphql/src/exceptions/io_network_exception.dart:14:31)
E/flutter (29368): #2      translateFailure (package:graphql/src/exceptions/exceptions.dart:13:10)
E/flutter (29368): #3      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart:104:38)
E/flutter (29368): <asynchronous suspension>
E/flutter (29368): #4      _runGuarded (dart:async/stream_controller.dart:807:24)
E/flutter (29368): #5      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:686:7)
E/flutter (29368): #6      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:416:13)
E/flutter (29368): #7      _StreamController._subscribe (dart:async/stream_controller.dart:685:18)
E/flutter (29368): #8      _ControllerStream._createSubscription (dart:async/stream_controller.dart:820:19)
E/flutter (29368): #9      _StreamImpl.listen (dart:async/stream_impl.dart:474:9)
E/flutter (29368): #10     new _AddStreamState (dart:async/stream_controller.dart:887:34)
E/flutter (29368): #11     new _StreamControllerAddStreamState (dart:async/stream_controller.dart:939:9)
E/flutter (29368): #12     _StreamController.addStream (dart:async/stream_controller.dart:562:13)
E/flutter (29368): #13     new AuthLink.<anonymous closure>.onListen (package:graphql/src/link/auth/link_auth.dart:27:32)
E/flutter (29368): <asynchronous suspension>
E/flutter (29368): #14     _runGuarded (dart:async/stream_controller.dart:807:24)
E/flutter (29368): #15     _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:686:7)
E/flutter (29368): #16     _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:416:13)
E/flutter (29368): #17     _StreamController._subscribe (dart:async/stream_controller.dart:685:18)
E/flutter (29368): #18     _ControllerStream._createSubscription (dart:async/stream_controller.dart:820:19)
E/flutter (29368): #19     _StreamImpl.listen (dart:async/stream_impl.dart:474:9)
E/flutter (29368): #20     Stream.first (dart:async/stream.dart:1251:25)
E/flutter (29368): #21     QueryManager._resolveQueryOnNetwork (package:graphql/src/core/query_manager.dart:119:9)
E/flutter (29368): #22     QueryManager.fetchQueryAsMultiSourceResult (package:graphql/src/core/query_manager.dart:97:17)
E/flutter (29368): #23     QueryManager.fetchQuery (package:graphql/src/core/query_manager.dart:75:9)
E/flutter (29368): #24     QueryManager.query (package:graphql/src/core/query_manager.dart:46:12)
E/flutter (29368): #25     GraphQLClient.query (package:graphql/src/graphql_client.dart:106:25)
E/flutter (29368): #26     GraphQlUtil.query (package:icy_client_sunmi/utils/graphql_util.dart:39:31)
E/flutter (29368): #27     LoginRepository.executeLogin (package:icy_client_sunmi/repository/login_repository.dart:8:38)
E/flutter (29368): #28     _LoginPageState._executeLogin (package:icy_client_sunmi/page/login_page.dart:528:36)
E/flutter (29368): #29     _LoginPageState._onLogin (package:icy_client_sunmi/page/login_page.dart:439:5)
E/flutter (29368): #30     _LoginPageState.build.<anonymous closure>.<anonymous closure> (package:icy_client_sunmi/page/login_page.dart:244:37)
E/flutter (29368): #31     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (29368): #32     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (29368): #33     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (29368): #34     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (29368): #35     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (29368): #36     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (29368): #37     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (29368): #38     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (29368): #39     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (29368): #40     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (29368): #41     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (29368): #42     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
```
Any suggestions would help me fix it, I would appreciate it

**Comment by tomhoule** [comment]
Hi @walterFeng - I think you are using a different library in dart, this repo is for the Rust graphql-client :)

**Comment by walterFeng** [comment]
@tomhoule sorry, I will close it later.
